services:
  glances:
    image: nicolargo/glances:4.4.1
    restart: unless-stopped
    pid: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # Uncomment the below line if you want glances to display host OS detail instead of container's
      - /etc/os-release:/etc/os-release:ro
      - /etc/hostname:/etc/hostname:ro
    ports:
      - 61208:61208
    environment:
      - "GLANCES_OPT=-w"
